function download(filename, text, type = "text/plain") {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function empireToMarkdown(empire) {
  if (!empire) return "# No empire\n";
  const lines = [
    `# ${empire.displayName}`,
    "",
    `**Handle:** \`${empire.handle}\`  `,
    `**Archetype:** ${empire.archetypeTitle || empire.archetype}  `,
    `**Constraint:** ${empire.constraint?.raw || ""}  `,
    "",
    "## Pitch",
    "",
    empire.pitch,
    "",
    "## Origin",
    "",
    empire.originStory,
    "",
    "## Resources (snapshot)",
    "",
    `- Capital: ₡${Math.round(empire.resources.capital)}`,
    `- Inventory: ${Math.round(empire.resources.inventory)}`,
    `- Reputation: ${Math.round(empire.resources.reputation)}`,
    `- Stress: ${Math.round(empire.resources.stress)}`,
    `- Heat: ${Math.round(empire.metrics.heat)}`,
    `- Market share: ${empire.metrics.marketShare.toFixed?.(1) ?? empire.metrics.marketShare}%`,
    "",
    "## Blueprints",
    "",
  ];

  for (const bp of empire.blueprints || []) {
    lines.push(`### [${bp.kind}] ${bp.title}`, "", bp.summary, "", "**Steps**", "");
    (bp.steps || []).forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push("", `**Materials:** ${(bp.materials || []).join(", ")}`, "", `**Risk:** ${bp.riskNote || "—"}`, "");
  }

  lines.push("---", "", "_Generated by ShadowMarket — constraint-native micro-empires._", "");
  return lines.join("\n");
}

export function exportMarkdown(empire) {
  const md = empireToMarkdown(empire);
  const slug = (empire?.displayName || "empire").toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  download(`shadowmarket-${slug}.md`, md, "text/markdown");
}

export function exportJSON(empire, extras = {}) {
  const payload = {
    exportedAt: new Date().toISOString(),
    app: "ShadowMarket",
    version: 1,
    empire,
    ...extras,
  };
  const slug = (empire?.displayName || "empire").toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  download(`shadowmarket-${slug}.json`, JSON.stringify(payload, null, 2), "application/json");
}

export function printBlueprints() {
  document.body.classList.add("print-blueprints");
  window.print();
  setTimeout(() => document.body.classList.remove("print-blueprints"), 500);
}
